Sprint 3
YanPrika/react-burger pull request #4
Opened 2023-10-05 12:35 UTC by YanPrika

2023-10-05 13:13 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Сильные стороны работы:
- Настроена защита роутов и редиректы
- Есть автологин
- Реализован механизм обновления токена
- Отличная работа с формами

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Делать запрос ингредиентов следует только в одном месте - App. У вас сейчас в двух и из-за этого запрос дублируется, а этого не следует допускать по возможности
- Не авторизованный юзер не должен иметь возможность сделать заказ
- Если попытаться зайти в профиль юзера не авторизованому юзеру, то после авторизации на странице профиля пустые инпуты. После перезагрузки страницы они заполняются.

<img width="945" alt="image" src="https://github.com/YanPrika/react-burger/assets/60173362/90f967a3-c319-4790-8905-10dcc0e1b771">

- Лого хедера обычно делают ссылкой на главную страницу

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-10-05 13:13 UTC, andryxxa93 commented on src/components/app/App.tsx
> +          path="/profile"
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-10-05 13:13 UTC, andryxxa93 commented on src/pages/IngredientPage/IngredientPage.tsx
> +    const { ingredients } = useSelector((store: any) => store.ingredients);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-10-06 10:13 UTC, YanPrika commented
Добрый день.
Внесены правки по Вашим замечаниям.

2023-10-06 12:40 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-10-15 16:55 UTC, merged